#################################################
#      Jagglessentials for Spigot Servers       #
#              Main Configuration               #
#################################################
