name: Jagglessentials
description: All the essentials for a generic server!
version: 1.10.2-0.0.1.0
author: Jagahkiin2014
website: https://github.com/Jagahkiin2014/Jagglessentials-Spigot
main: com.github.jagahkiin2014.Jagglessentials.Jagglessentials

commands:
    announce:
        description: Make a serverwide announcement.
        aliases: [say, broadcast, notice]
    ban:
        description: Ban a player from the server permanently.
    banip:
        description: Ban an IP from the server.
    clear:
        description: Clear the inventory of player.
        aliases: [clearinventory, ci]
    clearhistory:
        description: Clear the ban and kick history of a player.
    feed:
        description: Feed a player.
    fly:
        description: Toggle fly for a player.
        aliases: soar
    gamemode:
        description: Change the gamemode of a player.
        aliases: [gm, setgamemode, setgm]
    give:
        description: Give an item to a player.
        aliases: [giveitem, item, i]
    god:
        description: Toggle god mode for a player.
    heal:
        description: Heal a player.
    kick:
        description: Kick a player from the server.
        aliases: boot
    mail:
        description: Mail a player a message.
    motd:
        description: Message of the day.
    mute:
        description: Mute a player.
    onplayers:
        description: List all online players.
    seen:
        description: Provides information on a player.
        aliases: [playerinfo, whois, uuid]
    sethome:
        description: Set a home.
    setspawn:
        description: Set spawn.
    spawn:
        description: Teleport to spawn.
    speed:
        description: Change the speed of a player.
    tban:
        description: Temporarily ban a player.
        aliases: tempban
    time:
        description: Get/set time of day.
    weather:
        description: Get/set weather.
        
permissions:
    je.*:
        description: Provides perms to all commands.
        default: op
        children:
            je.seen.*: true
    je.seen.*:
        description: Provides perms to all seen info.
        default: op
        children:
            je.seen.normal: true
            je.seen.staff: true
    je.seen.normal:
        description: Provides perms to player info for generally normal players.
    je.seen.staff:
        description: Provides perms to player info for generally staff players.
        default: op
    je.seen.ip:
        description: Provides perms to player info to see a player's IP address.
